import React from 'react';
import classes from './CV.module.css';

const CV = props => {
    return (
        <div className={classes.CV}>
            <div className={classes.Heading}>
                <h2>Billy Smith | Front End Developer</h2>
                <p>Brentford, London</p>
                <p>07717325656</p>
                <p>billy@billysmith.net</p>
            </div>
            <div className={classes.Body}>
                <h3>Personal Profile</h3>
                <p>I have a great self drive and a passion to continuously learn. After my first exerience of development in my final year of university I wanted to learn more but decided against paying for more education. I took lockdown as an opportunity to learn HTML, CSS and Javascript, finding my first client for freelance work in May. Wanting to build more than static websites I began learning React in July and have since furthered my skills through a series of projects, showcased on my portfolio website.</p>
                <h3>Core Skills</h3>
                <table>
                    <tr><td><strong>Languages</strong></td><td>HTML/JSX, CSS, Javascript, Python, Solidity</td></tr>
                    <tr><td><strong>Frameworks</strong></td><td>React.js, Express, Truffle</td></tr>
                    <tr><td><strong>Other</strong></td><td>Unix/Linux, AWS, Firebase, Photoshop</td></tr>
                </table>
                <h3>Education</h3>
                <p><strong>BSc (Hons) Physics [2:1]</strong> Bristol University (2016-2019)</p>
                <p><strong>A-levels:</strong></p>
                <table>
                    <tr><td><strong>Physics</strong></td><td>A</td></tr>
                    <tr><td><strong>Mathematics</strong></td><td>B</td></tr>
                    <tr><td><strong>Psychology</strong></td><td>B</td></tr>
                </table>
                <h3>Relevant Work Experience &amp; Projects</h3>
                <div className={classes.JobHeadline}>
                    <p><strong>Freelance Web Development</strong></p><p>March 2019 - Present</p>
                </div>
                <p>I worked with clients to realise their needs, created mockup designs in Photoshop before building whole websites front to back using CSS, HTML, JS and Node. I acted on feedback quickly to work towards a solution that the client felt was their own.</p>
                <p>I saved clients 80% of hosting fees using efficient cloud computing methods (AWS EC2).</p>
                <p>I learned technologies as required by clients (Webmail, AWS, Express).</p>
                <p><span onClick = {() => window.open("https://www.biographicalcounselling.net/")}>biographicalcounselling.net</span></p>
                <div className={classes.JobHeadline}>
                    <p><strong>React Portfolio Projects</strong></p><p>July 2020 - Present</p>
                </div>
                <p>I planned and built a <span onClick = {() => window.open("https://master.d1l4h4map9o1uj.amplifyapp.com/")}>collaborative bugtracker web application</span> using React and Firebase, allowing users to create bug reports, comment on bugs and manage their urgency to name a few features.</p>
                <p>I built a <span onClick = {() => window.open("https://main.d1og6uu514ow0q.amplifyapp.com/")}>cryptocurrency trading game</span> using React. The prices are generated by an algorithm and the user can place market and limit orders on several different coins, each with their own price behaiviour.</p>
                <p>This website is built with React, and runs as a single page application using the React router. It also allows me to create blog posts so I can collate and share my research into various topics of interest.</p>
                <div className={classes.JobHeadline}>
                    <p><strong>Open Day Operations Assistant</strong></p><p>University of Bristol</p><p>April 2019 - October 2019</p>
                </div>
                <p>I was responsible for organising and distributing all equipment for the 2019 open days, attended by thousands of people.</p>
                <p>Efficient communication with a large and varied team was essential, both in the months leading up to the event and on the day.</p>
                <p>I led several teams of student workers, assigning jobs as issues arose to ensure a smooth running of the event, representing the university to the highest standard.</p>
                <h3>Other Interests and Activities</h3>
                <p>Learning about emerging privacy technologies - zk-SNARKS, STARKs, SNORKs.</p>
                <p>Participating in and learning about the Ethereum ecosystem - attending virtual conferences, experimenting with dApps, reaching out to members of the community.</p>
                <p>Digital art</p>
                <p>I meditate and play guitar to get away from my computer</p>
                <p style = {{textAlign: 'center', fontWeight: 400, marginTop: "50px"}}>References available on request</p>
            </div>
        </div>
    )
}

export default CV